apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - 1password-connect.yaml
  - cilium.yaml
  - external-secrets.yaml
  - metrics-server.yaml
  - kube-state-metrics.yaml
  - opentelemetry.yaml
  - httpbin.yaml
  - namespaces.yaml
  - cert-manager.yaml
  - kuberay-operator.yaml
